### ISSUE TITLE
Black upper screen when running payload

### ISSUE THREAD

**Issue by Manteric** [capito27/Pasta-CFW#1]
O3DS 9.2 EU
Using the default Lexar 4GB SDHC
Followed the instructions on the video and loaded successfully the payload.
I'm not able to run it, since the upper screen remains black (sometimes I get two colored pixels on the bottom left of the screen, one purple, one green), while the lower screen says [+]  Running ARM9 payload.
Also tried to reformat the SD using the windows tool, but nothing changed.

**Comment by motezazer** [comment]
You just have to reinstall Ninjhax.
