### ISSUE TITLE
fatfs: really need support 932(Shift-jis) encoding?

### ISSUE THREAD

**Issue by Syphurith** [capito27/Pasta-CFW#10]
As you can see in `CFW_loader/source/fatfs` now, there are `cc*.c` files.
Maybe you just forgot to set _CODE_PAGE in `ffconf.h` to the one you need.
I have ever tried the FATFS ago, and thus configuration would increase the size of your `elf`.
Even I don't know if there is any sense with space usage, i don't think you would need Shift-JIS.

```
932  - Japanese Shift-JIS (DBCS, OEM, Windows)
936  - Simplified Chinese GBK (DBCS, OEM, Windows)
949  - Korean (DBCS, OEM, Windows)
950  - Traditional Chinese Big5 (DBCS, OEM, Windows)
```

**Comment by AlbertoSONIC** [comment]
I'm using the FATFS provided with Archshift's decrypt9, so idk...

**Comment by Syphurith** [comment]
@AlbertoSONIC cc932.c would be included if _CODE_PAGE == 932.
If you only want to support ASCII chars, and don't need to support those filenames including Shift-JIS (Japanese) chars.. The data in the file would sound useless to you.
Simply enough you can try to compile one with just ASCII and test if that suites your need.

**Comment by Syphurith** [comment]
Well please forget that. I've build it with 932 and 850, however only difference within 1KB. So sorry.

However fatfs could be mini, cause we don't even touch `f_readdir`, or something similar. Yep 2KB. 
@AlbertoSONIC ~~And for [devkitPro](http://devkitpro.org/viewtopic.php?f=13&t=8409&sid=6f536d1d90369ce871335dd69fb7cf6a) it said 3ds app should use `-mfloat-abi=hard`. I've seen some symbols related to the float point, but still unaware of the effect.~~ well no hard VFP for thumb.
