### ISSUE TITLE
Comments, function names, ?

### ISSUE THREAD

**Issue by Syphurith** [capito27/Pasta-CFW#11]
I know this CFW is a piece of work by HACKERS. However i know the result of no comment or document about the code itself. Even HACKER may forget something he wrote days before.
So, mind someone read the code and try to add some comments about what is done in the functions?
**Note** This may cause someone wait for confirms in pulls. Yes you can write some yourself.

For the function names.. There are names that not so .. properly chosen..
Sometime the name just confuse me, as `ClearTop` in `main.c`. It may be one that clear both screens..
I don't know if you use any IDE to write the code. But for C.. Global defined functions and variables may cause conflicts if their names are not well chosen when it is somehow big enough.
**Note** I had my day when i found two defined `KeyPressed` in my project which has 30+ files..

Also some functions are not properly placed, like.. ClearTop, this could be placed in `draw.c`, according to its purpose. If properly placed it saved your time when you wanna find it.

_If annoyed by my words or think these are not important at all, please tell me and let me close this._
Pasta CFW is indeed promising.. ~~If someone add those features as Emunand support.~~

**Comment by AlbertoSONIC** [comment]
You're completely right. If you see my github projects, are all well commented and explained. This code is a mess, but I have to find some time to clear it up!

**Comment by Syphurith** [comment]
Ok i know now. Many thanks to you. Mind me list all those `inproper` placed/named ones, or even try to deal those myself? _Well maybe a `Note for Developers` or `Note for Testers` first._
BTW i forget to tell your about the `uint8_t`, `u8` and `unsigned char`.
It took me seconds to recall its size, minutes ago. Should all be `u8` ~~or `uint8_t`~~ yep.

**Comment by felipejfc** [comment]
thanks for the suggestions, friend, feel free to send a pull request with the code-optimizations you find suitable :)

**Comment by Syphurith** [comment]
Thanks for your permission. I would try to read some days later.

**Comment by Syphurith** [comment]
@AlbertoSONIC @felipejfc Added comments and Renamed some names. [Here](https://github.com/Syphurith/Pasta-CFW/tree/re-code). based on #17.
