### ISSUE TITLE
Doesn't work for Old 3DS owners (1.0 only)

### ISSUE THREAD

**Issue by motezazer** [capito27/Pasta-CFW#4]
Many users on GBATemp are complaining that the new version give them a black screen.

**Comment by deltabeard** [comment]
Doesn't work on 3DS XL 9.2.0-20 E with 1.0 beta release.

**Comment by MrJPGames** [comment]
When holding L it shows the correct firmware and 3DS type (o3DS 4.5) but when launching CFW it doesn't actually patch sig checks.

**Comment by motezazer** [comment]
Fixed with latest commit
