### ISSUE TITLE
6.2.0-12U: Potentially Does not Work

### ISSUE THREAD

**Issue by Some1Else46** [capito27/Pasta-CFW#8]
Unless I am somehow doing something wrong, 6.2.0-12U does not fully work. I am using pasta-Cfw 1.2 on ninjhax 1.1b. I have done the title.db trick and the system settings did do its fix. Although pasta-Cfw does successfully launch, when I relaunch ninjhax, FBI still does not work. Although it will try to install a CIA and get to about 50%, the install will still fail, which leads me to believe that the signature checks are not disabled.
![img_1578](https://cloud.githubusercontent.com/assets/5633257/7849652/809a2f66-048c-11e5-9bb9-ef65320f434f.JPG)

**Comment by urherenow** [comment]
The problem is with your .CIA, not pastaCFW. It won't even begin to install and will give a different error, if the sig checks weren't patched out.
